// Dummy data for distributors and products
export const distributors = [
  {
    id: 1,
    name: "GreenLeaf Distributors",
    image: "/distributors/greenleaf.png",
    description: "Leading supplier of organic and eco-friendly products.",
    categories: ["Groceries", "Organic"],
  },
  {
    id: 2,
    name: "UrbanMart",
    image: "/distributors/urbanmart.png",
    description: "Your daily essentials at the best price.",
    categories: ["Groceries", "Essentials"],
  },
  {
    id: 3,
    name: "AgroPro",
    image: "/distributors/agropro.png",
    description: "Wholesale agricultural products direct from farms.",
    categories: ["Agriculture", "Groceries"],
  },
];

export const products = [
  {
    id: 1,
    name: "Organic Basmati Rice",
    distributorId: 1,
    distributor: "GreenLeaf Distributors",
    price: 78.5,
    quantity: 50,
    description: "Finest long-grain organic basmati rice, perfect for healthy meals.",
    image: "/products/rice.png",
  },
  {
    id: 2,
    name: "Fresh Tomatoes",
    distributorId: 3,
    distributor: "AgroPro",
    price: 32.0,
    quantity: 200,
    description: "Farm-fresh, juicy tomatoes delivered daily.",
    image: "/products/tomatoes.png",
  },
  {
    id: 3,
    name: "Whole Wheat Flour",
    distributorId: 2,
    distributor: "UrbanMart",
    price: 45.0,
    quantity: 120,
    description: "Premium quality whole wheat flour for soft, healthy rotis.",
    image: "/products/flour.png",
  },
  {
    id: 4,
    name: "Organic Green Tea",
    distributorId: 1,
    distributor: "GreenLeaf Distributors",
    price: 120.0,
    quantity: 40,
    description: "Refreshing and healthy organic green tea leaves.",
    image: "/products/greentea.png",
  },
  {
    id: 5,
    name: "Potatoes (5kg)",
    distributorId: 3,
    distributor: "AgroPro",
    price: 110.0,
    quantity: 80,
    description: "Bulk fresh potatoes, perfect for restaurants and caterers.",
    image: "/products/potatoes.png",
  },
  {
    id: 6,
    name: "Cooking Oil",
    distributorId: 2,
    distributor: "UrbanMart",
    price: 150.0,
    quantity: 60,
    description: "High-quality sunflower cooking oil for all your kitchen needs.",
    image: "/products/oil.png",
  },
];
